In [2]:
import numpy

In [3]:
class G():
    def __init__(self):
        self.x = 5

In [4]:
a = G()

In [5]:
a

In [6]:
a.x

5

In [7]:
b = a

In [8]:
b.x

5

In [9]:
a.x = 2

In [10]:
b.x

2

In [14]:
c = numpy.random.rand(12)

In [16]:
c

array([ 0.78991496,  0.17779763,  0.74004123,  0.1403738 ,  0.26217835,
        0.48065783,  0.76358755,  0.72325521,  0.95066473,  0.1350198 ,
        0.58557274,  0.74944466])

In [18]:
c.reshape([3,4])

array([[ 0.78991496,  0.17779763,  0.74004123,  0.1403738 ],
       [ 0.26217835,  0.48065783,  0.76358755,  0.72325521],
       [ 0.95066473,  0.1350198 ,  0.58557274,  0.74944466]])

In [19]:
c

array([ 0.78991496,  0.17779763,  0.74004123,  0.1403738 ,  0.26217835,
        0.48065783,  0.76358755,  0.72325521,  0.95066473,  0.1350198 ,
        0.58557274,  0.74944466])

In [21]:
a = [[1, 1, 1], [1, 0, 1]]


In [27]:
a[1].count(1)



2